Repository angular/material.angular.io, pull requests merged in 2018-10, with the labels that each got.

#527 chore: capitalization on nav item and enable commented out examples
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#534 chore: add v6 firebase project and update deploy script
  package-lock.json
  tools/deploy.sh
Labels: cla: yes

#535 chore: use breakpoint observer for sidenav
  src/app/pages/component-sidenav/component-sidenav.html
  src/app/pages/component-sidenav/component-sidenav.spec.ts
  src/app/pages/component-sidenav/component-sidenav.ts
Labels: cla: yes

#524 Added dropdown icon to version picker
  src/app/shared/version-picker/version-picker.html
  src/app/shared/version-picker/version-picker.ts
Labels: cla: yes

#537 chore: update to v7
  package.json
  src/app/shared/documentation-items/documentation-items.ts
  tools/deploy.sh
Labels: cla: yes

#538 chore: update 5.x branch to include new versions
  package-lock.json
  package.json
  src/app/shared/version-picker/version-picker.html
  src/app/shared/version-picker/version-picker.ts
  src/app/shared/version/version.ts
Labels: cla: yes

#540 feat: change navbar, toolbar and landing page coloring to denote when looking at docs on next
  package-lock.json
  src/_app-theme.scss
  src/app/pages/homepage/homepage.html
  src/app/pages/homepage/homepage.ts
  src/app/shared/footer/footer.html
  src/app/shared/footer/footer.ts
  src/app/shared/navbar/navbar.html
  src/app/shared/navbar/navbar.ts
Labels: cla: yes

#543 build: fix CI tests after change to postinstall script
  scripts/ci/build-and-test.sh
Labels: cla: yes

#542 build: support NodeJS 10.x
  .travis.yml
  package-lock.json
  package.json
  src/app/shared/navbar/navbar.spec.ts
Labels: cla: yes

#545 fix: table of contents not working within cdk
  src/app/material-docs-app.ts
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready

#547 fix(scrolling): add ScrollingModule
  src/assets/stackblitz/material-module.ts
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready

#549 feat: add the ability to link to the site with a particular theme
  package-lock.json
  src/app/shared/theme-picker/theme-picker.html
  src/app/shared/theme-picker/theme-picker.spec.ts
  src/app/shared/theme-picker/theme-picker.ts
  src/app/shared/theme-picker/theme-storage/theme-storage.spec.ts
  src/app/shared/theme-picker/theme-storage/theme-storage.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#541 docs(readme): update contributing instructions
  README.md
Labels: P3: important, cla: yes, docs, pr: lgtm

#555 fix(main): don't load hammerjs twice
  src/main.ts
Labels: cla: yes, pr: lgtm, pr: merge ready
