Repository angular/material.angular.io, pull requests merged in 2018-02, with the labels that each got.

#384 better styling for deprecated api items
  src/app/pages/component-viewer/component-api.scss
  src/styles/_api.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#386 fix(stackblitz): update angular dependencies for stackblitz to latest
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes

#387 chore: update versions and make sw config more specific
  package-lock.json
  package.json
  src/app/shared/stackblitz/stackblitz-writer.ts
  src/ngsw-config.json
Labels: cla: no

#392 chore: update docs site to use 5.2.1 release
  package-lock.json
  package.json
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes, pr: needs review

#390 feat(stackblitz): start sb on index #373
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes

#397 chore: add moment and @angular/material-moment-adapter deps to stackblitz
  src/app/shared/stackblitz/stackblitz-writer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes, pr: needs review

#399 fix: update title background #398
  src/styles/_api-theme.scss
Labels: cla: yes

#401 chore: send analytics data on all navigation ends
  src/app/app-module.ts
  src/app/material-docs-app.ts
  src/app/shared/ga/ga.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
Labels: cla: yes, pr: lgtm, pr: merge ready

#400 fix(stackblitz): fix svg path getting extra /app
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes
