Repository angular/material.angular.io, pull requests merged in 2018-09, with the labels that each got.

#514 docs: show text-field, coercion and platform in CDK docs
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#512 feat: add summaries to all menu items and category pages
  src/app/pages/component-category-list/component-category-list.html
  src/app/pages/component-category-list/component-category-list.scss
  src/app/pages/component-category-list/component-category-list.ts
  src/app/pages/component-list/_component-list-theme.scss
  src/app/pages/component-list/component-list.html
  src/app/pages/component-list/component-list.scss
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/navbar/navbar.html
Labels: cla: yes

#516 feat(example-viewer): support rendering additional files
  package-lock.json
  package.json
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#518 build: fix continuous integration
  .travis.yml
  browser-providers.js
  karma-custom-launchers.js
  karma.conf.js
  package-lock.json
  package.json
  scripts/browserstack/block-tunnel.sh
  scripts/browserstack/start-tunnel.sh
  scripts/browserstack/teardown-tunnel.sh
  scripts/ci/build-and-test.sh
  scripts/ci/travis-mode.sh
  scripts/ci/travis-tunnel.sh
  scripts/saucelabs/block-tunnel.sh
  scripts/saucelabs/start-tunnel.sh
  scripts/saucelabs/teardown-tunnel.sh
  src/app/pages/component-category-list/component-category-list.spec.ts
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/example-viewer/example-viewer.ts
  src/unregister-service-workers.ts
  tools/fetch-assets.sh
  tools/print-publish-branch.js
Labels: cla: yes, pr: lgtm, pr: merge ready

#520 chore: expose all chips examples under examples tab
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#494 feat: add ripples to documentation items
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: merge ready

#519 fix: anchor links not scrolling into view
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-examples.html
  src/app/pages/component-viewer/component-overview.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/guide-viewer/guide-viewer.html
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/doc-viewer/header-link.ts
  src/app/shared/navigation-focus/navigation-focus.ts
Labels: cla: yes, pr: lgtm, pr: merge ready
