Repository angular/material.angular.io, pull requests merged in 2018-08, with the labels that each got.

#500 fix: horizontal scrollbar always visible on Windows in code samples
  src/app/shared/example-viewer/_example-viewer-theme.scss
Labels: cla: yes, pr: merge ready

#503 fix: remove service worker
  angular.json
  ngsw-config.json
  package-lock.json
  package.json
  src/app/app-module.ts
  src/main.ts
  src/unregister-service-workers.ts
Labels: cla: yes, pr: needs review

#504 Remove cache-control header from firebase.json
  firebase.json
Labels: cla: yes

#505 build: ensure docs-content is up-to-date before deploy
  tools/deploy.sh
  tools/fetch-assets.sh
Labels: cla: yes, pr: lgtm, pr: merge ready
