Repository angular/material.angular.io, pull requests merged in 2018-07, with the labels that each got.

#480 chore: v 6.3.2
  package-lock.json
  package.json
  src/app/shared/version/version.ts
Labels: cla: yes

#477 chore: show all autocomplete examples in examples tab
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#481 chore: fix lint warning
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready

#482 chore: update the version picker to use the currently running verison.
  src/app/shared/version-picker/version-picker.ts
  src/app/shared/version/version.ts
Labels: cla: yes

#483 update to 6.3.3
  package-lock.json
  package.json
Labels: cla: yes

#489 feat: add ripples to documentation items
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: needs review, target: next minor version

#491 chore: bump material version
  package.json
Labels: cla: yes

#493 Revert "feat: add ripples to documentation items"
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes
