Repository angular/material.angular.io, pull requests merged in 2018-05, with the labels that each got.

#434 Add doc items for tree and badge
  package-lock.json
  package.json
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#433 fix: fix 'reporters' key name in karma.conf
  karma.conf.js
Labels: cla: yes

#435 Move from Http to HttpClient
  package-lock.json
  src/app/app-module.ts
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.ts
  src/app/shared/style-manager/style-manager.spec.ts
  src/app/shared/svg-viewer/svg-viewer.ts
  src/app/testing/testing-module.ts
  src/assets/stackblitz/main.ts
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: needs rebase

#437 Add tree module to stackblitz NgModule
  src/assets/stackblitz/main.ts
Labels: cla: yes

#438 Fix name of schematics guide html file
  src/app/shared/guide-items/guide-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#440 Enable version picker for 5.x
  src/app/shared/navbar/navbar.html
  src/app/shared/version/version.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#441 Use npm bin for deploy script in 5.x
  tools/deploy.sh
Labels: cla: yes, pr: lgtm, pr: merge ready

#442 Use npm bin for deploy script in master
  tools/deploy.sh
Labels: cla: yes, pr: lgtm, pr: merge ready

#445 fix: set rootUrl during construction of table of contents
  src/app/shared/table-of-contents/table-of-contents.ts
Labels: cla: yes

#443 chore: Use CdkAccordionItems for component-nav
  src/app/pages/component-sidenav/component-nav.html
  src/app/pages/component-sidenav/component-sidenav.ts
Labels: cla: yes

#447 chore: add MatBadgeModule to stackblitz main.ts file.
  src/assets/stackblitz/main.ts
Labels: cla: yes, pr: lgtm

#448 chore: update to 6.0.1
  package-lock.json
  package.json
  src/app/shared/version/version.ts
Labels: cla: yes

#449 fix: menu icons example not rendering
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: needs review

#450 Update dependency versions
  package-lock.json
  package.json
Labels: cla: yes, pr: lgtm, pr: merge ready

#451 fix: footer not sticking to bottom of the page on IE
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#454 chore: update package version to 6.1
  package-lock.json
  package.json
  src/app/shared/version/version.ts
Labels: cla: yes

#459 chore: update to 6.2.0
  package-lock.json
  package.json
  src/app/shared/version/version.ts
Labels: cla: yes
