Repository angular/material.angular.io, pull requests merged in 2018-03, with the labels that each got.

#407 chore: bump version to 5.2.4
  package.json
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#406 feat: add version and version picker
  package.json
  src/app/shared/footer/footer.ts
  src/app/shared/navbar/navbar.html
  src/app/shared/navbar/navbar.ts
  src/app/shared/stackblitz/stackblitz-writer.ts
  src/app/shared/version-picker/index.ts
  src/app/shared/version-picker/version-picker.html
  src/app/shared/version-picker/version-picker.ts
  src/app/shared/version/version.ts
  tools/deploy.sh
Labels: cla: yes, pr: lgtm, pr: merge ready

#410 fix(component-viewer): can't navigate to CDK after visiting component
  src/app/pages/component-viewer/component-viewer.ts
Labels: cla: yes

#411 fix(tests): fix tests on CI
  .travis.yml
  package-lock.json
  package.json
  src/app/pages/component-list/component-list.spec.ts
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.spec.ts
  src/app/shared/footer/footer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: cla: yes

#385 chore: add bottom sheet examples
  src/app/shared/documentation-items/documentation-items.ts
  src/assets/stackblitz/main.ts
Labels: cla: yes, pr: needs review

#337 style: match stackblitz and example viewer padding
  src/assets/stackblitz/styles.css
Labels: cla: yes

#417 fix(ga): set analytics for mat and ng separately
  src/app/shared/ga/ga.ts
Labels: cla: yes

#418 fix(ga): remove extra '/'
  src/app/shared/ga/ga.ts
Labels: cla: yes

#415 docs: add schematics link
  src/app/shared/guide-items/guide-items.ts
Labels: cla: yes
