Repository angular/material.angular.io, pull requests merged in 2019-09, with the labels that each got.

#616 fix: add missing drag-drop examples
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#631 refactor: enable stricter TypeScript compiler flags
  src/app/pages/component-list/component-list.ts
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.spec.ts
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/guide-viewer/guide-viewer.html
  src/app/pages/guide-viewer/guide-viewer.spec.ts
  src/app/pages/guide-viewer/guide-viewer.ts
  src/app/shared/copier/copier.service.ts
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/guide-items/guide-items.ts
  src/app/shared/stackblitz/stackblitz-writer.spec.ts
  src/app/shared/svg-viewer/svg-viewer.ts
  src/app/shared/table-of-contents/table-of-contents.spec.ts
  src/app/shared/table-of-contents/table-of-contents.ts
  src/app/shared/theme-picker/theme-picker.ts
  src/tsconfig.json
Labels: P3: important, cla: yes, refactoring

#637 fix(a11y): improve contrast of accent in pink-bluegrey theme
  src/assets/custom-themes/pink-bluegrey.scss
Labels: P3: important, a11y, cla: yes

#636 build: update package.json script to use yarn
  package.json
Labels: P2: required, cla: yes, infrastructure

#635 fix(a11y): various issues with contrast ratios
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/guide-list/_guide-list-theme.scss
  src/app/shared/table-of-contents/_table-of-contents-theme.scss
  src/highlightjs/material-dark.scss
  src/highlightjs/material-light.scss
  src/styles/_api-theme.scss
  src/styles/_markdown-theme.scss
Labels: P2: required, a11y, cla: yes

#634 build: fix object might be undefined error in template
  src/app/pages/component-list/component-list.html
Labels: P1: urgent, cla: yes

#632 chore: add issue template
  .github/ISSUE_TEMPLATE/docs-infra.md
Labels: P2: required, cla: yes, infrastructure

#633 chore: add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: P4: nice to have, cla: yes, infrastructure
