Repository angular/material.angular.io, pull requests merged in 2019-11, with the labels that each got.

#672 build: Angular CLI update to 9.0.0-rc.0
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz/src/app/material-module.ts
  src/assets/stack-blitz/src/styles.scss
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure, pr: merge ready

#673 build: update to new package name for examples package
  README.md
  angular.json
  package.json
  src/app/app-module.ts
  src/app/pages/component-viewer/component-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
  src/app/shared/stack-blitz/stack-blitz-button.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  tools/deploy.sh
  yarn.lock
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready

#675 build: Angular and CLI update to 9.0.0-rc.1
  package.json
  src/assets/stack-blitz/package.json
  yarn.lock
Labels: P3: important, cla: yes, infrastructure

#677 update to material & cdk 9.0.0-rc.1
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#678 feat: add cdk/testing docs
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/guide-items/guide-items.ts
Labels: P1: urgent, cla: yes

#680 bump to 9.0.0-rc.3
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#681 Rename `Testing > Testing` to `Testing > Component Harnesses`
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#682 Add styles for async methods marker
  src/styles/_api-theme.scss
  src/styles/_api.scss
  src/styles/_tables.scss
Labels: cla: yes, pr: lgtm
