Repository angular/material.angular.io, pull requests merged in 2019-08, with the labels that each got.

#601 fix(manifest.json): use rel paths, remove density
  src/assets/img/favicons/manifest.json
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready

#614 Typo
  src/app/shared/stackblitz/stackblitz-button.ts
Labels: P4: nice to have, cla: yes, pr: lgtm, pr: merge ready

#619 update to 8.1.3
  package.json
  yarn.lock
Labels: cla: yes
