Repository angular/material.angular.io, pull requests merged in 2019-10, with the labels that each got.

#640 Update to components 8.2
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#641 refactor: convert app to latest Angular CLI format
  .gitignore
  angular.json
  e2e/app.e2e-spec.ts
  e2e/app.po.ts
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/tsconfig.json
  package.json
  src/app/app-module.ts
  src/app/pages/component-sidenav/component-sidenav.html
  src/app/pages/component-sidenav/component-sidenav.spec.ts
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/routes.ts
  src/app/shared/navigation-focus/navigation-focus.ts
  src/app/shared/stackblitz/stackblitz-writer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.ts
  src/app/shared/theme-picker/theme-picker.ts
  src/app/shared/version-picker/version-picker.ts
  src/environments/environment.ts
  src/main.ts
  src/polyfills.ts
  src/tsconfig.json
  src/tsconfig.spec.json
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure, refactoring

#642 fix: prepare for enabling Ivy
  package.json
  src/app/shared/stackblitz/stackblitz-writer.spec.ts
  src/app/shared/stackblitz/stackblitz-writer.ts
  src/app/shared/version-picker/version-picker.html
  src/app/shared/version-picker/version-picker.ts
  src/assets/stackblitz/.angular-cli.json
  src/assets/stackblitz/polyfills.ts
  yarn.lock
Labels: P2: required, cla: yes, infrastructure, refactoring

#646 Update to 8.2.3
  package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure

#647 build: enable Ivy for 8.x
  tsconfig.app.json
Labels: P3: important, cla: yes, pr: merge ready

#648 Update docs and StackBlitz Angular to 9.0.0-next.10
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/app/shared/version-picker/version-picker.html
  src/assets/stack-blitz/angular.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure, refactoring

#652 refactor: remove duplicate css declaration
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: P4: nice to have, cla: yes, pr: lgtm, pr: merge ready

#651 fix(docs): correct overflow cdk pages
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready

#654 fix(component-sidenav): apply CSS fixes from master to 8.x
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: P3: important, cla: yes, pr: merge ready

#649 fix: accessibility, SEO, typos, styling, favicons
  angular.json
  src/_app-theme.scss
  src/app/pages/homepage/homepage.html
  src/app/pages/page-title/page-title.ts
  src/app/shared/footer/footer.html
  src/app/shared/footer/footer.scss
  src/assets/img/angular-material-logo.svg
  src/assets/img/favicons/android-chrome-144x144.png
  src/assets/img/favicons/android-chrome-192x192.png
  src/assets/img/favicons/android-chrome-36x36.png
  src/assets/img/favicons/android-chrome-48x48.png
  src/assets/img/favicons/android-chrome-512x512.png
  src/assets/img/favicons/android-chrome-72x72.png
  src/assets/img/favicons/android-chrome-96x96.png
  src/assets/img/favicons/apple-touch-icon-144x144.png
  src/assets/img/favicons/apple-touch-icon-152x152.png
  src/assets/img/favicons/apple-touch-icon-180x180.png
  src/assets/img/favicons/apple-touch-icon-precomposed.png
  src/assets/img/favicons/apple-touch-icon.png
  src/assets/img/favicons/browserconfig.xml
  src/assets/img/favicons/favicon-16x16.png
  src/assets/img/favicons/favicon-194x194.png
  src/assets/img/favicons/favicon-32x32.png
  src/assets/img/favicons/favicon-96x96.png
  src/assets/img/favicons/favicon.ico
  src/assets/img/favicons/manifest.json
  src/assets/img/favicons/mstile-150x150.png
  src/assets/img/favicons/safari-pinned-tab.svg
  src/assets/img/site-preview.png
  src/favicon.ico
  src/index.html
  src/robots.txt
  src/sitemap.xml
  src/styles.scss
  tools/deploy.sh
Labels: P2: required, cla: yes, infrastructure, refactoring

#653 refactor: styles refactoring. disable commonChunk
  angular.json
  src/_app-theme.scss
  src/styles.scss
Labels: P3: important, cla: yes, pr: merge ready

#656 fix: accessibility, SEO, typos, styling, favicons (from 8.x to master)
  angular.json
  src/app/pages/homepage/homepage.html
  src/app/pages/page-title/page-title.ts
  src/app/shared/footer/footer.html
  src/app/shared/footer/footer.scss
  src/assets/img/angular-material-logo.svg
  src/assets/img/favicons/android-chrome-144x144.png
  src/assets/img/favicons/android-chrome-192x192.png
  src/assets/img/favicons/android-chrome-36x36.png
  src/assets/img/favicons/android-chrome-48x48.png
  src/assets/img/favicons/android-chrome-512x512.png
  src/assets/img/favicons/android-chrome-72x72.png
  src/assets/img/favicons/android-chrome-96x96.png
  src/assets/img/favicons/apple-touch-icon-144x144.png
  src/assets/img/favicons/apple-touch-icon-152x152.png
  src/assets/img/favicons/apple-touch-icon-180x180.png
  src/assets/img/favicons/apple-touch-icon-precomposed.png
  src/assets/img/favicons/apple-touch-icon.png
  src/assets/img/favicons/browserconfig.xml
  src/assets/img/favicons/favicon-16x16.png
  src/assets/img/favicons/favicon-194x194.png
  src/assets/img/favicons/favicon-32x32.png
  src/assets/img/favicons/favicon-96x96.png
  src/assets/img/favicons/favicon.ico
  src/assets/img/favicons/manifest.json
  src/assets/img/favicons/mstile-150x150.png
  src/assets/img/favicons/safari-pinned-tab.svg
  src/assets/img/site-preview.png
  src/favicon.ico
  src/index.html
  src/robots.txt
  src/sitemap.xml
Labels: P2: required, cla: yes, pr: merge ready

#650 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: P4: nice to have, cla: yes, pr: merge ready

#657 fix api docs content from displaying after the left nav
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: P1: urgent, cla: yes, pr: lgtm, pr: merge ready

#658 8.x: fix api docs content from displaying after the left nav
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: P1: urgent, cla: yes

#659 build: update to Angular 9.0.0-next.11 and CLI 9.0.0-next.12
  package.json
  src/app/pages/component-list/component-list.html
  src/app/pages/component-sidenav/component-sidenav.html
  src/app/pages/homepage/homepage.html
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/theme-picker/theme-picker.html
  yarn.lock
Labels: P2: required, cla: yes, infrastructure, pr: merge ready

#660 add option for additional api docs for testing harnesses
  src/app/pages/component-sidenav/component-sidenav.scss
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-examples.html
  src/app/pages/component-viewer/component-overview.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/guide-viewer/guide-viewer.html
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/table-of-contents/table-of-contents.html
  src/app/shared/table-of-contents/table-of-contents.scss
  src/app/shared/table-of-contents/table-of-contents.spec.ts
  src/app/shared/table-of-contents/table-of-contents.ts
Labels: P2: required, cla: yes, feature, infrastructure, pr: needs cleanup / tests

#663 fix(category-list): bad routerLink path with relativeLinkResolution
  src/app/pages/component-category-list/component-category-list.html
Labels: P2: required, caretaker note, cla: yes, pr: merge ready

#668 fix: apply updates from master to 8.x branch
  src/app/pages/component-category-list/component-category-list.html
  src/app/shared/stack-blitz/stack-blitz-button.html
Labels: P2: required, cla: yes

#667 fix(stack-blitz-button): use open_in_new icon
  src/app/shared/stack-blitz/stack-blitz-button.html
Labels: P4: nice to have, cla: yes

#669 docs(cdk/clipboard): add to docs site
  src/app/shared/documentation-items/documentation-items.ts
Labels: P2: required, cla: yes, infrastructure, pr: lgtm, pr: merge ready

#670 build: ng update dependencies and install peerDeps
  angular.json
  package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure
