Repository angular/material.angular.io, pull requests merged in 2020-01, with the labels that each got.

#696 build: update to Angular CLI v9 rc.7 and Components v9 rc.6
  package.json
  src/assets/stack-blitz/src/polyfills.ts
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure

#700 bump version to 9.0.0-rc.7
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#699 build: update to Angular and CLI v9 rc.8 and Components v9 rc.7
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  yarn.lock
Labels: P2: required, cla: yes, infrastructure, pr: merge ready

#698 Lazy load documentation modules
  src/app/app-module.ts
  src/app/pages/component-category-list/component-category-list.ts
  src/app/pages/component-list/component-list.ts
  src/app/pages/component-page-header/component-page-header.ts
  src/app/pages/component-sidenav/component-sidenav-can-load-guard.ts
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/guide-list/guide-list.ts
  src/app/pages/guide-viewer/guide-viewer.ts
  src/app/pages/homepage/homepage.ts
  src/app/pages/page-title/page-title.ts
  src/app/routes.ts
  src/app/shared/doc-viewer/doc-viewer-module.ts
  src/app/shared/ga/ga.ts
  src/app/shared/navbar/navbar.ts
Labels: P3: important, cla: yes, infrastructure, perf

#703 build: update to components 9.0.0-rc.8
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes, infrastructure

#697 docs-infra: address numerous a11y issues
  e2e/src/app.e2e-spec.ts
  package.json
  src/app/material-docs-app.html
  src/app/pages/component-page-header/component-page-header.html
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/component-sidenav/component-nav.html
  src/app/pages/component-sidenav/component-sidenav.html
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-overview.html
  src/app/pages/component-viewer/component-viewer.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/guide-list/guide-list.html
  src/app/pages/homepage/homepage.html
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/doc-viewer/header-link.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/navbar/navbar.html
  src/app/shared/navigation-focus/navigation-focus.ts
  src/app/shared/stack-blitz/stack-blitz-button.html
  src/app/shared/stack-blitz/stack-blitz-button.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/app/shared/style-manager/style-manager.spec.ts
  src/app/shared/svg-viewer/svg-viewer.ts
  src/app/shared/table-of-contents/table-of-contents.html
  src/app/shared/theme-picker/theme-picker.html
  src/app/shared/theme-picker/theme-picker.scss
  src/app/shared/theme-picker/theme-picker.spec.ts
  src/app/shared/theme-picker/theme-picker.ts
  src/app/shared/theme-picker/theme-storage/theme-storage.ts
  src/app/shared/version-picker/version-picker.html
  src/app/shared/version-picker/version-picker.ts
  src/assets/img/theme-demo-icon.svg
  tslint.json
Labels: P2: required, cla: yes, infrastructure, pr: lgtm, pr: merge ready

#702 build: update to Angular CLI 9.0.0-rc.9
  package.json
  yarn.lock
Labels: P4: nice to have, cla: yes, infrastructure, pr: merge ready

#706 build: update to Angular 9.0.0-rc.11 and CLI 9.0.0-rc.10
  package.json
  yarn.lock
Labels: P2: required, cla: yes

#707 build: update to Angular 9.0.0-rc.12, CLI 9.0.0-rc.11, and Components 9.0.0-rc.9
  package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure

#708 Hide text content in homepage svg
  src/assets/img/homepage/sprintzerotoapp.svg
Labels: a11y, cla: yes, pr: lgtm, pr: merge ready
