Repository angular/material.angular.io, pull requests merged in 2020-07, with the labels that each got.

#809 add table scene
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/table/table-scene.html
  scenes/src/app/scenes/table/table-scene.scss
  scenes/src/app/scenes/table/table-scene.ts
Labels: cla: yes

#810 add bottom sheet scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/bottom-sheet/bottom-sheet-scene.html
  scenes/src/app/scenes/bottom-sheet/bottom-sheet-scene.scss
  scenes/src/app/scenes/bottom-sheet/bottom-sheet-scene.ts
  src/assets/screenshots/bottom-sheet.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#808 Add scene for snackbar
  package.json
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/snack-bar/snack-bar-scene.scss
  scenes/src/app/scenes/snack-bar/snack-bar-scene.ts
  src/assets/screenshots/snack-bar.scene.png
Labels: cla: yes

#816 add expansion scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/expansion/expansion-scene.html
  scenes/src/app/scenes/expansion/expansion-scene.scss
  scenes/src/app/scenes/expansion/expansion-scene.ts
  src/assets/screenshots/expansion.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#819 add select scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scene-viewer/scene-viewer.scss
  scenes/src/app/scenes/select/select-scene.html
  scenes/src/app/scenes/select/select-scene.scss
  scenes/src/app/scenes/select/select-scene.ts
  src/assets/screenshots/select.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#812 add autcomplete scenes
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/autocomplete/autocomplete-scene.html
  scenes/src/app/scenes/autocomplete/autocomplete-scene.ts
  src/assets/screenshots/autocomplete.scene.png
Labels: cla: yes

#815 add grid list scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/grid-list/grid-list-scene.html
  scenes/src/app/scenes/grid-list/grid-list-scene.scss
  scenes/src/app/scenes/grid-list/grid-list-scene.ts
  src/assets/screenshots/grid-list.scene.png
Labels: cla: yes

#821 fix: copy to clipboard button always copying content of first tab
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.ts
Labels: cla: yes

#820 add tree scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/tree/tree-scene.html
  scenes/src/app/scenes/tree/tree-scene.scss
  scenes/src/app/scenes/tree/tree-scene.ts
  src/assets/screenshots/tree.scene.png
Labels: cla: yes

#811 tabs scene
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/tabs/tabs-scene.html
  scenes/src/app/scenes/tabs/tabs-scene.scss
  scenes/src/app/scenes/tabs/tabs-scene.ts
Labels: cla: yes

#813 sort scene
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/sort/sort-scene.html
  scenes/src/app/scenes/sort/sort-scene.scss
  scenes/src/app/scenes/sort/sort-scene.ts
Labels: cla: yes

#817 add card scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/card/card-scene.html
  scenes/src/app/scenes/card/card-scene.scss
  scenes/src/app/scenes/card/card-scene.ts
  src/assets/screenshots/card.scene.png
Labels: cla: yes

#814 List scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/list/list-scene.html
  scenes/src/app/scenes/list/list-scene.scss
  scenes/src/app/scenes/list/list-scene.ts
  src/assets/screenshots/list.scene.png
Labels: cla: yes

#818 add tooltip scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/tooltip/tooltip-scene.html
  scenes/src/app/scenes/tooltip/tooltip-scene.scss
  scenes/src/app/scenes/tooltip/tooltip-scene.ts
  src/assets/screenshots/tooltip.scene.png
Labels: cla: yes

#807 add dialog scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/dialog/dialog-scene.html
  scenes/src/app/scenes/dialog/dialog-scene.ts
  scenes/src/styles.scss
  src/assets/screenshots/dialog.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#823 add form-field scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/form-field/form-field-scene.html
  scenes/src/app/scenes/form-field/form-field-scene.ts
  src/assets/screenshots/form-field.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#824 add toolbar scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/toolbar/toolbar-scene.html
  scenes/src/app/scenes/toolbar/toolbar-scene.scss
  scenes/src/app/scenes/toolbar/toolbar-scene.ts
  src/assets/screenshots/toolbar.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#822 add sidenav scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/sidenav/sidenav-scene.html
  scenes/src/app/scenes/sidenav/sidenav-scene.scss
  scenes/src/app/scenes/sidenav/sidenav-scene.ts
  src/assets/screenshots/sidenav.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#825 add icon scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/icon/icon-scene.html
  scenes/src/app/scenes/icon/icon-scene.scss
  scenes/src/app/scenes/icon/icon-scene.ts
  src/assets/screenshots/icon.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#827 fix: homepage not using native accelerated scrolling on touch devices
  src/app/material-docs-app.scss
Labels: cla: yes

#780 landing page redesign
  src/_app-theme.scss
  src/app/pages/homepage/_homepage-theme.scss
  src/app/pages/homepage/homepage.html
  src/app/pages/homepage/homepage.scss
  src/app/pages/homepage/homepage.ts
  src/app/shared/carousel/_carousel-theme.scss
  src/app/shared/carousel/carousel.html
  src/app/shared/carousel/carousel.scss
  src/app/shared/carousel/carousel.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#829 bump version to 10.0.2
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready

#831 update site-preview image
  src/assets/img/site-preview.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#830 docs(readme): add v9 and v10 links
  README.md
Labels: P3: important, cla: yes, docs, pr: lgtm

#832 fix: home page in mobile view
  src/app/pages/homepage/homepage.scss
Labels: cla: yes

#834 fix: footer jumping up while guide is loading
  src/app/pages/guide-viewer/guide-viewer.scss
Labels: cla: yes

#836 docs-bug(CDK:Overlay): Stackblitz example broken
  src/assets/stack-blitz/src/app/material-module.ts
Labels: cla: yes

#837 refactor: prepare for docs-content changes in v10.1
  package.json
  projects/sub/src/assets/hello.css
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
  yarn.lock
Labels: cla: yes

#838 chore: bump to 10.1.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#839 fix: footer not being pushed to the bottom of the page in guides
  src/app/pages/guide-viewer/guide-viewer.scss
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready

#841 fix: remove extension from Stackblitz examples
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#842 chore: fix double file extension
  src/app/shared/stack-blitz/stack-blitz-writer.ts
Labels: cla: yes
