Repository angular/material.angular.io, pull requests merged in 2020-02, with the labels that each got.

#709 build: update to Angular 9.0.0-rc.14 and CLI to 9.0.0-rc.12
  package.json
  yarn.lock
Labels: P3: important, cla: yes, infrastructure, pr: lgtm, pr: merge ready

#705 fix: numerous responsive issues on screens from 360px to 960px
  src/app/pages/component-category-list/component-category-list.ts
  src/app/pages/component-page-header/component-page-header.scss
  src/app/pages/component-sidenav/component-sidenav.html
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-api.scss
  src/app/pages/guide-list/guide-list.scss
  src/app/pages/guide-viewer/guide-viewer.scss
  src/app/shared/footer/footer.html
  src/styles/_api.scss
  src/styles/_constants.scss
  src/styles/_tables.scss
Labels: P2: required, cla: yes, infrastructure

#710 build: update to Components 9.0.0-rc.10 and Angular CLI 9.0.0-rc.14
  package.json
  src/assets/versions.json
  yarn.lock
Labels: P3: important, cla: yes, infrastructure

#714 Update everything to v9
  README.md
  package.json
  src/assets/stack-blitz/package.json
  src/assets/versions.json
  tools/deploy.sh
  yarn.lock
Labels: cla: yes

#712 fix(stack-blitz): default to form-field fill appearance
  src/assets/stack-blitz/src/main.ts
Labels: P2: required, cla: yes, docs, infrastructure, pr: merge ready

#716 fix: cdk test harness API document not found
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#717 fix: components with multiple API docs do not display correctly
  src/app/pages/component-viewer/component-api.html
Labels: cla: yes

#719 fix(guide): add ReactiveFormsModule to GuideViewerModule
  src/app/pages/guide-viewer/guide-viewer.ts
Labels: P2: required, cla: yes

#722 build: lazily load examples in docs site
  package.json
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  yarn.lock
Labels: P2: required, cla: yes

#723 bump to @angular/material 9.0.1
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#724 build: use better resource class for building in circleci
  .circleci/config.yml
Labels: cla: yes

#725 chore: update to Components 9.1.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#727 add table-reorderable example
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes
