Repository angular/material.angular.io, pull requests merged in 2020-05, with the labels that each got.

#757 fix: expose component testing modules
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: lgtm

#746 Pre-build themes using Angular CLI (sass + sass-loader) instead of node-sass Bash script
  angular.json
  package.json
  src/_app-theme.scss
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/component-viewer/_component-viewer-theme.scss
  src/app/pages/guide-list/_guide-list-theme.scss
  src/app/pages/guide-viewer/guide-viewer.scss
  src/styles/_api-theme.scss
  src/styles/_constants.scss
  src/styles/_markdown-theme.scss
  src/styles/_svg-theme.scss
  src/styles/_tables-theme.scss
  src/styles/custom-themes/deeppurple-amber.scss
  src/styles/custom-themes/indigo-pink.scss
  src/styles/custom-themes/pink-bluegrey.scss
  src/styles/custom-themes/purple-green.scss
  tools/build-themes.sh
  yarn.lock
Labels: P3: important, cla: yes, infrastructure, pr: merge ready, refactoring

#756 feat: compact view for example components to replace static code snippets
  src/app/pages/component-viewer/component-examples.html
  src/app/shared/doc-viewer/doc-viewer-module.ts
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/example-viewer/_example-viewer-theme.scss
  src/app/shared/example-viewer/code-snippet.html
  src/app/shared/example-viewer/code-snippet.ts
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.scss
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
Labels: cla: yes

#761 patch: fix incorrect prefix for loading examples
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#762 build: update dependencies. fix audit warnings. update copyrights
  LICENSE
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz/package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, infrastructure, pr: lgtm, pr: merge ready

#758 enable compact view examples
  src/app/pages/component-viewer/component-examples.html
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/example-viewer/_example-viewer-theme.scss
  src/app/shared/example-viewer/code-snippet.html
  src/app/shared/example-viewer/code-snippet.ts
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
Labels: cla: yes, pr: lgtm, pr: merge ready
