Repository angular/material.angular.io, pull requests merged in 2020-04, with the labels that each got.

#742 Fragment link navigation padding
  src/styles/_markdown.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#745 add skip navigation link
  src/app/material-docs-app.scss
  src/app/material-docs-app.ts
  src/app/pages/component-category-list/component-category-list.html
  src/app/pages/component-category-list/component-category-list.ts
  src/app/pages/component-page-header/component-page-header.html
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-examples.html
  src/app/pages/component-viewer/component-overview.html
  src/app/pages/component-viewer/component-viewer.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/guide-list/guide-list.html
  src/app/pages/guide-list/guide-list.ts
  src/app/pages/guide-viewer/guide-viewer.html
  src/app/pages/guide-viewer/guide-viewer.ts
  src/app/pages/homepage/homepage.html
  src/app/pages/homepage/homepage.ts
  src/app/shared/navbar/navbar.html
  src/app/shared/navbar/navbar.scss
  src/app/shared/navbar/navbar.ts
  src/app/shared/navigation-focus/navigation-focus.ts
Labels: cla: yes

#749 rename example to reflect change in @angular/components-example
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#750 auto load examples from @angular/components-examples
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#752 fix(stack-blitz): v7 demos fail when trying to load v9 dependencies
  src/app/shared/stackblitz/stackblitz-writer.ts
Labels: P2: required, cla: yes, infrastructure

#751 refactor: create a service to manage navigation & focus state in the docs app
  src/app/material-docs-app.scss
  src/app/material-docs-app.ts
  src/app/pages/component-category-list/component-category-list.html
  src/app/pages/component-list/component-list.html
  src/app/pages/component-list/component-list.ts
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.html
  src/app/pages/guide-list/guide-list.html
  src/app/pages/guide-viewer/guide-viewer.html
  src/app/pages/homepage/homepage.html
  src/app/shared/navbar/navbar.html
  src/app/shared/navbar/navbar.ts
  src/app/shared/navigation-focus/navigation-focus.service.ts
  src/app/shared/navigation-focus/navigation-focus.spec.ts
  src/app/shared/navigation-focus/navigation-focus.ts
  src/app/shared/table-of-contents/table-of-contents.ts
Labels: cla: yes, pr: lgtm

#755 Change stackblitz theme to indigo-pink
  src/assets/stack-blitz/src/styles.scss
Labels: cla: yes
