Repository angular/material.angular.io, pull requests merged in 2020-06, with the labels that each got.

#766 use screenshot test to capture scenes for components
  angular.json
  package.json
  scenes/browserslist
  scenes/e2e/protractor.conf.js
  scenes/e2e/screenshot.ts
  scenes/e2e/src/app.e2e-spec.ts
  scenes/e2e/src/app.po.ts
  scenes/e2e/tsconfig.json
  scenes/karma.conf.js
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.component.scss
  scenes/src/app/app.component.spec.ts
  scenes/src/app/app.component.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scene-viewer/scene-viewer.html
  scenes/src/app/scene-viewer/scene-viewer.scss
  scenes/src/app/scene-viewer/scene-viewer.ts
  scenes/src/environments/environment.prod.ts
  scenes/src/environments/environment.ts
  scenes/src/favicon.ico
  scenes/src/index.html
  scenes/src/main.ts
  scenes/src/polyfills.ts
  scenes/src/styles.scss
  scenes/src/test.ts
  scenes/tsconfig.app.json
  scenes/tsconfig.spec.json
  scenes/tslint.json
Labels: cla: yes, pr: lgtm, pr: merge ready

#774 change from using host property to using @HostBinding
  scenes/src/app/scene-viewer/scene-viewer.ts
Labels: cla: yes, pr: lgtm

#779 add font and make scene viewer a flex box for easy centering
  scenes/src/app/scene-viewer/scene-viewer.scss
  scenes/src/styles.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#760 restructure doc items
  src/_app-theme.scss
  src/app/pages/component-category-list/_component-category-list-theme.scss
  src/app/pages/component-category-list/component-category-list.html
  src/app/pages/component-category-list/component-category-list.scss
  src/app/pages/component-category-list/component-category-list.spec.ts
  src/app/pages/component-list/_component-list-theme.scss
  src/app/pages/component-list/component-list.html
  src/app/pages/component-list/component-list.scss
  src/app/pages/component-list/component-list.spec.ts
  src/app/pages/component-list/component-list.ts
  src/app/pages/component-list/index.ts
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/component-sidenav/component-nav.html
  src/app/pages/component-sidenav/component-sidenav.scss
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.scss
  src/app/shared/documentation-items/documentation-items.spec.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/footer/footer.scss
Labels: cla: yes, pr: lgtm

#783 Merge branch "next-v10" into master
  package.json
  src/assets/versions.json
  tools/deploy.sh
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready

#776 add ripples scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/ripples/ripples-scene.html
  scenes/src/app/scenes/ripples/ripples-scene.scss
  scenes/src/app/scenes/ripples/ripples-scene.ts
  src/assets/screenshots/ripples.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#772 add slider scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/slider/slider-scene.html
  scenes/src/app/scenes/slider/slider-scene.scss
  scenes/src/app/scenes/slider/slider-scene.ts
  scenes/src/styles.scss
  src/assets/screenshots/slider.scene.png
Labels: cla: yes, pr: lgtm

#777 add button-toggle scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/button-toggle/button-toggle-scene.html
  scenes/src/app/scenes/button-toggle/button-toggle-scene.ts
  scenes/src/styles.scss
  src/assets/screenshots/button-toggle.scene.png
  src/assets/screenshots/input.scene.png
  src/assets/screenshots/slider.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#773 add slide-toggle scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/slide-toggle/slide-toggle-scene.html
  scenes/src/app/scenes/slide-toggle/slide-toggle-scene.scss
  scenes/src/app/scenes/slide-toggle/slide-toggle-scene.ts
  src/assets/screenshots/slide-toggle.scene.png
Labels: cla: yes

#775 add divider scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/divider/divider-scene.html
  scenes/src/app/scenes/divider/divider-scene.scss
  scenes/src/app/scenes/divider/divider-scene.ts
  src/assets/screenshots/divider.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#788 add scene route for every component
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/placeholder/_placeholder-scene-theme.scss
  scenes/src/app/scenes/placeholder/placeholder-scene.html
  scenes/src/app/scenes/placeholder/placeholder-scene.scss
  scenes/src/app/scenes/placeholder/placeholder-scene.ts
  src/assets/screenshots/button-toggle.scene.png
  src/assets/screenshots/divider.scene.png
  src/assets/screenshots/input.scene.png
  src/assets/screenshots/ripples.scene.png
  src/assets/screenshots/slide-toggle.scene.png
  src/assets/screenshots/slider.scene.png
Labels: cla: yes, pr: lgtm

#784 follow-up improvements to components list page
  src/app/pages/component-category-list/_component-category-list-theme.scss
  src/app/pages/component-category-list/component-category-list.html
  src/app/pages/component-category-list/component-category-list.scss
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#771 add progress-spinner scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/progress-spinner/progress-spinner-scene.html
  scenes/src/app/scenes/progress-spinner/progress-spinner-scene.scss
  scenes/src/app/scenes/progress-spinner/progress-spinner-scene.ts
  src/assets/screenshots/progress-spinner.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#767 add button scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/button/button-scene.html
  scenes/src/app/scenes/button/button-scene.scss
  scenes/src/app/scenes/button/button-scene.ts
  src/assets/screenshots/button.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#768 add datepicker scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/datepicker/datepicker-scene.html
  scenes/src/app/scenes/datepicker/datepicker-scene.scss
  scenes/src/app/scenes/datepicker/datepicker-scene.ts
  scenes/src/styles.scss
  src/assets/screenshots/datepicker.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#769 add checkbox scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/checkbox/checkbox-scene.html
  scenes/src/app/scenes/checkbox/checkbox-scene.scss
  scenes/src/app/scenes/checkbox/checkbox-scene.ts
  src/assets/screenshots/checkbox.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#791 add chips scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/chips/chips-scene.html
  scenes/src/app/scenes/chips/chips-scene.scss
  scenes/src/app/scenes/chips/chips-scene.ts
  src/assets/screenshots/chips.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#789 add progress bar scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/progress-bar/progress-bar-scene.html
  scenes/src/app/scenes/progress-bar/progress-bar-scene.scss
  scenes/src/app/scenes/progress-bar/progress-bar-scene.ts
  src/assets/screenshots/progress-bar.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#793 add stepper scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/stepper/stepper-scene.html
  scenes/src/app/scenes/stepper/stepper-scene.scss
  scenes/src/app/scenes/stepper/stepper-scene.ts
  src/assets/screenshots/stepper.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#786 horizontal carousel for guide list on landing page
  src/app/shared/carousel/carousel-module.ts
  src/app/shared/carousel/carousel.html
  src/app/shared/carousel/carousel.scss
  src/app/shared/carousel/carousel.spec.ts
  src/app/shared/carousel/carousel.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#799 Update to Angular 10.0.0
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz/package.json
  src/assets/versions.json
  tools/deploy.sh
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready

#797 custom overlay container
  scenes/src/app/app.module.ts
  scenes/src/app/scene-overlay-container.ts
  scenes/src/app/scene-viewer/scene-viewer.html
Labels: cla: yes, pr: lgtm, pr: merge ready

#794 add radio button scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/radio/radio-scene.html
  scenes/src/app/scenes/radio/radio-scene.scss
  scenes/src/app/scenes/radio/radio-scene.ts
  src/assets/screenshots/radio.scene.png
Labels: cla: yes

#798 center skip link
  src/app/shared/navbar/navbar.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#803 fix(guides): fix the positioning of the footer on the guides page
  src/app/pages/guide-list/guide-list.html
  src/app/pages/guide-list/guide-list.scss
  src/app/pages/guide-list/guide-list.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#802 set scale on container
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scene-viewer/scene-viewer.ts
  src/assets/screenshots/button-toggle.scene.png
  src/assets/screenshots/checkbox.scene.png
  src/assets/screenshots/datepicker.scene.png
  src/assets/screenshots/divider.scene.png
  src/assets/screenshots/input.scene.png
  src/assets/screenshots/progress-bar.scene.png
  src/assets/screenshots/progress-spinner.scene.png
  src/assets/screenshots/radio.scene.png
  src/assets/screenshots/ripple.scene.png
  src/assets/screenshots/slide-toggle.scene.png
  src/assets/screenshots/slider.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#800 add overviews for guides
  src/app/shared/guide-items/guide-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#801 fix(component-category-list): links fail a11y contrast checks in dark mode
  src/app/pages/component-category-list/_component-category-list-theme.scss
Labels: P2: required, a11y, cla: yes

#804 add menu scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/menu/menu-scene.html
  scenes/src/app/scenes/menu/menu-scene.scss
  scenes/src/app/scenes/menu/menu-scene.ts
  src/assets/screenshots/menu.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#795 add badge scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/badge/badge-scene.html
  scenes/src/app/scenes/badge/badge-scene.scss
  scenes/src/app/scenes/badge/badge-scene.ts
  src/assets/screenshots/badge.scene.png
Labels: cla: yes, pr: lgtm, pr: merge ready

#790 add paginator scene
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/app.module.ts
  scenes/src/app/scenes/paginator/paginator-scene.html
  scenes/src/app/scenes/paginator/paginator-scene.scss
  scenes/src/app/scenes/paginator/paginator-scene.ts
  src/assets/screenshots/paginator.scene.png
Labels: cla: yes

#806 update code snippet view
  src/index.html
  src/styles/_markdown-theme.scss
Labels: cla: yes, pr: lgtm, pr: merge ready

#805 Update to Angular components and framework 10.0.1
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready
