Repository angular/material.angular.io, pull requests merged in 2020-11, with the labels that each got.

#883 update to 11.0.0-rc.1
  angular.json
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#872 feat(stackblitz): add new stackblitz template to run harness test examples
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/stack-blitz/stack-blitz-button.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz-tests/.editorconfig
  src/assets/stack-blitz-tests/.gitignore
  src/assets/stack-blitz-tests/angular.json
  src/assets/stack-blitz-tests/browserslist
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz-tests/src/app/material-module.ts
  src/assets/stack-blitz-tests/src/index.html
  src/assets/stack-blitz-tests/src/main.ts
  src/assets/stack-blitz-tests/src/polyfills.ts
  src/assets/stack-blitz-tests/src/styles.scss
  src/assets/stack-blitz-tests/src/test.ts
  src/assets/stack-blitz-tests/src/test/jasmine-setup.ts
  src/assets/stack-blitz-tests/tsconfig.app.json
  src/assets/stack-blitz-tests/tsconfig.json
  src/assets/stack-blitz-tests/tsconfig.spec.json
  src/assets/stack-blitz-tests/tslint.json
Labels: cla: yes, pr: merge ready

#885 release: update next to 11.0.0-rc.4
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#887 update deploy script for v11 release
  src/assets/versions.json
  tools/deploy.sh
Labels: cla: yes

#886 bump to version 11
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#888 refactor: fixes for breaking changes, deprecations, and other adjustments in v11
  .browserslistrc
  LICENSE
  README.md
  angular.json
  firebase.json
  package.json
  scenes/src/app/app.component.spec.ts
  scenes/src/app/app.module.ts
  src/app/pages/component-category-list/component-category-list.spec.ts
  src/app/pages/component-page-header/component-page-header.spec.ts
  src/app/pages/component-sidenav/component-sidenav.spec.ts
  src/app/pages/component-viewer/component-viewer.spec.ts
  src/app/pages/guide-list/guide-list.spec.ts
  src/app/pages/guide-viewer/guide-viewer.spec.ts
  src/app/shared/carousel/carousel.spec.ts
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/documentation-items/documentation-items.spec.ts
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/footer/footer.spec.ts
  src/app/shared/guide-items/guide-items.spec.ts
  src/app/shared/navbar/navbar.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/app/shared/table-of-contents/table-of-contents.spec.ts
  src/app/shared/theme-picker/theme-picker.spec.ts
  src/assets/stack-blitz-tests/.browserslistrc
  src/assets/stack-blitz-tests/angular.json
  src/assets/stack-blitz-tests/browserslist
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz-tests/src/styles.scss
  src/assets/stack-blitz-tests/tsconfig.json
  src/assets/stack-blitz/.browserslistrc
  src/assets/stack-blitz/angular.json
  src/assets/stack-blitz/browserslist
  src/assets/stack-blitz/package.json
  src/assets/stack-blitz/tsconfig.json
  src/environments/environment.ts
  tools/deploy.sh
  tsconfig.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, infrastructure, pr: lgtm, pr: merge ready, refactoring

#876 fix(button): fix color of mat-button links
  src/styles/_markdown-theme.scss
Labels: cla: yes

#895 bump version to 11.0.1
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes
