Repository angular/material.angular.io, pull requests merged in 2020-03, with the labels that each got.

#729 refactor: account for collision avoidance changes to docs-content
  src/app/pages/component-viewer/component-overview.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/app/shared/stack-blitz/stack-blitz-button.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  yarn.lock
Labels: P2: required, cla: yes, pr: lgtm

#732 fix: explicitly set an index for each API docs section
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-viewer.ts
  src/app/shared/table-of-contents/table-of-contents.ts
Labels: cla: yes, infrastructure

#730 Follow up to example-viewer for collision docs-content change
  src/app/shared/example-viewer/example-viewer.spec.ts
  src/app/shared/example-viewer/example-viewer.ts
Labels: P2: required, cla: yes, infrastructure

#734 fix: ripple overview not loading
  src/app/shared/documentation-items/documentation-items.ts
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready

#735 chore: ng update @angular/core @angular/cli @angular/material
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/versions.json
  yarn.lock
Labels: P3: important, cla: yes, infrastructure

#736 update to angular material 9.2.0-next.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#737 chore(ci): workaround ngcc crash due to running out of memory
  package.json
  yarn.lock
Labels: P3: important, cla: yes, infrastructure

#740 bump to version 9.2.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes
