Repository angular/material.angular.io, pull requests merged in 2020-08, with the labels that each got.

#848 Use `img` element in component list w/ lazy loading
  src/app/pages/component-category-list/component-category-list.html
  src/app/pages/component-category-list/component-category-list.scss
Labels: cla: yes

#845 docs(button): Exclude toggle button examples from button examples.
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#711 build: update 8.x branch to Angular CLI 8.3.29 and fix CircleCI
  .circleci/config.yml
  package.json
  tools/build-themes.sh
  yarn.lock
Labels: P3: important, cla: yes, infrastructure, pr: merge ready

#854 fix: some testing entry points referring to wrong module
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#853 chore: update to 10.1.3
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready

#855 fix: avoid breaking page if there's a broken example
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.ts
Labels: cla: yes

#850 reformat guides page using cards
  src/app/pages/guide-list/_guide-list-theme.scss
  src/app/pages/guide-list/guide-list.html
  src/app/pages/guide-list/guide-list.scss
  src/app/pages/guide-list/guide-list.ts
Labels: cla: yes

#856 fix: router outlet should not allow overflow
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: cla: yes
