Repository angular/material.angular.io, pull requests merged in 2021-01, with the labels that each got.

#866 build: fix angular cli commonjs warnings for polyfills
  angular.json
  src/assets/stack-blitz/src/main.ts
  src/environments/environment.ts
  src/main.ts
Labels: P3: important, cla: yes

#901 fix: generated Stackblitz examples not working when forked to a repo
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz/src/index.html
  src/assets/stack-blitz/src/styles.scss
Labels: cla: yes

#902 feat: add 404 page
  src/_app-theme.scss
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/not-found/_not-found-theme.scss
  src/app/pages/not-found/index.ts
  src/app/pages/not-found/not-found.html
  src/app/pages/not-found/not-found.scss
  src/app/pages/not-found/not-found.ts
  src/app/routes.ts
Labels: cla: yes

#900 fix: use new Google Fonts snippet
  src/index.html
Labels: cla: yes

#904 ci: set up lighthouse
  .circleci/config.yml
  package.json
  tools/audit-docs-a11y.js
  tools/audit-docs.js
  tools/lighthouse-audit.js
  yarn.lock
Labels: P3: important, a11y, cla: yes, infrastructure, perf, pr: lgtm

#903 build: update Angular, CLI, firebase-tools, ts-node, tslint, tslib
  package.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure

#907 build: update to Angular 11.1.0
  package.json
  yarn.lock
Labels: cla: yes, infrastructure

#908 release: update to 11.1.x
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes, pr: merge ready
