Repository angular/material.angular.io, pull requests merged in 2021-09, with the labels that each got.

#1060 fix: include cdkAccordionModule in material-module for accordion stackblitz demo
  src/assets/stack-blitz/src/app/material-module.ts
Labels: cla: yes

#1062 build: release 13.0.0-next.4
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#1063 build: release with 12.2.5
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#1065 fix: remove duplicated meta tag
  src/index.html
Labels: cla: yes, P4: nice to have, pr: merge ready, pr: lgtm

#1064 build: ng update CLI and core. update to NodeJS 16.6.0
  .circleci/config.yml
  .nvmrc
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  yarn.lock
Labels: P2: required, cla: yes, pr: merge ready, infrastructure, pr: lgtm, dependencies

#1071 bump to 13.0.0-next.6
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#1072 bump to 12.2.7
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#1073 bump to 12.2.7
  src/assets/versions.json
Labels: cla: yes

#1074 fix: update yarn.lock and fix package.json
  package.json
  yarn.lock
Labels: cla: yes

#1075 fix: use more lenient version when generating stackblitz
  src/app/shared/footer/footer.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/app/shared/version-picker/version-picker.ts
  src/app/shared/version/version.ts
Labels: cla: yes

#1077 fix: temporarily disable Ivy on Stackblitz (#1050)
  src/assets/stack-blitz/tsconfig.json
Labels: P2: required, cla: yes, infrastructure

#1079 fix: use more lenient version when generating stackblitz (#1075)
  src/app/shared/footer/footer.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/app/shared/version-picker/version-picker.ts
  src/app/shared/version/version.ts
Labels: cla: yes

#1078 bump to 12.2.8
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#1080 bump to 13.0.0-next.7
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes
