Repository angular/material.angular.io, pull requests merged in 2021-02, with the labels that each got.

#840 fix(material-docs-app): remove absolute positioning of all content
  src/app/material-docs-app.scss
  src/app/pages/guide-list/guide-list.ts
  src/app/pages/guide-viewer/guide-viewer.ts
  src/app/pages/homepage/homepage.ts
  src/app/pages/not-found/not-found.ts
  src/app/shared/navbar/navbar.scss
  src/styles/_general.scss
  tools/audit-docs-a11y.js
Labels: P3: important, cla: yes, infrastructure

#878 fix(toc): visibility on resizing
  src/app/pages/component-viewer/component-viewer.ts
  src/app/shared/doc-viewer/doc-viewer.ts
Labels: P3: important, cla: yes, pr: lgtm, pr: merge ready

#912 fix(component-viewer): Loading document... getting wrapped
  src/app/pages/component-viewer/component-api.html
  src/app/pages/component-viewer/component-viewer.scss
Labels: P3: important, cla: yes, infrastructure

#917 fix(component-sidenav,component-viewer): fix sticky TOC
  .nvmrc
  LICENSE
  README.md
  angular.json
  src/app/material-docs-app.scss
  src/app/pages/component-category-list/_component-category-list-theme.scss
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/component-sidenav/component-sidenav.scss
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.scss
  src/app/pages/guide-viewer/guide-viewer.scss
  src/app/pages/homepage/_homepage-theme.scss
  src/styles/_constants.scss
  src/styles/custom-themes/deeppurple-amber.scss
  src/styles/custom-themes/indigo-pink.scss
  src/styles/custom-themes/pink-bluegrey.scss
  src/styles/custom-themes/purple-green.scss
  tools/audit-docs.js
  tools/lighthouse-audit.js
  yarn.lock
Labels: P2: required, cla: yes

#913 fix(toc): quickly switching to API tab can throw exceptions
  src/app/shared/table-of-contents/table-of-contents.html
Labels: P3: important, cla: yes, infrastructure

#918 build: update to 11.1.2
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz/package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, infrastructure

#920 release: bump components version to 11.2.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#921 fix: add styling for markdown tables
  src/styles/_markdown-theme.scss
  src/styles/_markdown.scss
Labels: cla: yes

#923 fix: declare duplicate theming guide
  src/app/shared/guide-items/guide-items.ts
Labels: P3: important, cla: yes, infrastructure

#922 feat: add button to copy link to example
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.ts
Labels: cla: yes

#914 feat: add CSP and recommended security headers to site
  firebase.json
  tools/audit-docs.js
Labels: P2: required, cla: yes, infrastructure, perf, pr: lgtm, pr: merge ready

#925 update to 11.2.2
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes
