Repository angular/material.angular.io, pull requests merged in 2021-06, with the labels that each got.

#1005 feat: expose CDK accordion docs
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#1006 update to 12.0.3
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#1007 fix: guides overlapping footer on narrow screens
  src/app/pages/guide-list/guide-list.scss
  src/app/pages/guide-list/guide-list.spec.ts
Labels: cla: yes

#1011 bump to 12.0.4
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#989 docs: Update v11 link in README.md file
  README.md
Labels: P3: important, cla: yes, docs

#1010 fix: fix cookies dialog button contrast
  src/app/shared/cookie-popup/_cookie-popup-theme.scss
  src/app/shared/cookie-popup/cookie-popup.html
Labels: P2: required, a11y, cla: yes, pr: lgtm, pr: merge ready

#999 feat: more flexible carousels and fix homepage alignment
  src/app/pages/homepage/_homepage-theme.scss
  src/app/pages/homepage/homepage.html
  src/app/pages/homepage/homepage.scss
  src/app/shared/carousel/carousel.html
  src/app/shared/carousel/carousel.scss
  src/app/shared/carousel/carousel.spec.ts
  src/app/shared/carousel/carousel.ts
Labels: P2: required, cla: yes, design, pr: lgtm, pr: merge ready

#1004 fix(material/api-theme): fix nav items hover/focus contrast
  src/app/shared/navbar/_navbar-theme.scss
  src/app/shared/navbar/navbar.html
Labels: P3: important, a11y, cla: yes, pr: lgtm, pr: merge ready

#1014 fix(material/theme): unselected theme picker
  src/app/shared/theme-picker/theme-picker.ts
Labels: P4: nice to have, cla: yes, pr: lgtm, pr: merge ready

#1002 refactor: remove default form field appearance in Stackblitz
  src/assets/stack-blitz/src/main.ts
Labels: cla: yes

#1003 fix: align and clean up table design
  src/styles/_markdown-theme.scss
  src/styles/_markdown.scss
  src/styles/_tables-theme.scss
  src/styles/_tables.scss
Labels: cla: yes

#1017 release: update angular material version to 12.1.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes, pr: merge ready

#1024 docs(readme): fix development setup list format
  README.md
Labels: P4: nice to have, cla: yes, docs

#1016 build: ng update Angular and CLI to 12.1.0
  package.json
  src/styles/_general.scss
  yarn.lock
Labels: P2: required, cla: yes, dependencies, pr: lgtm, pr: merge ready

#1025 fix: add postinstall script back to make component examples work
  package.json
Labels: cla: yes
