Repository angular/material.angular.io, pull requests merged in 2021-05, with the labels that each got.

#972 build: update MDC to match the version required by v11.2.2+
  package.json
  yarn.lock
Labels: P3: important, cla: yes, dependencies, pr: lgtm

#968 chore: update 11.x branch to point to latest versions.json
  firebase.json
  src/app/shared/version-picker/version-picker.ts
  src/assets/versions.json
Labels: P3: important, cla: yes, infrastructure, pr: lgtm, pr: merge ready

#974 update next.material.angular.io to 12.0.0-rc.2
  package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, pr: lgtm

#973 chore: update Angular Material version to 11.2.12
  package.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, pr: lgtm

#979 fix(version-picker): restore the versions.json
  firebase.json
  package.json
  src/assets/versions.json
  yarn.lock
Labels: P1: urgent, cla: yes, pr: lgtm

#978 fix(sidenav): unable to scroll sidenav as expected
  src/app/pages/component-sidenav/component-sidenav.scss
Labels: P2: required, cla: yes, pr: lgtm

#984 release: bump to 12.0.0
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#915 feat: add help/support section
  src/_app-theme.scss
  src/app/pages/homepage/homepage.html
  src/app/pages/homepage/homepage.ts
  src/app/shared/support/support.html
  src/app/shared/support/support.scss
  src/app/shared/support/support.spec.ts
  src/app/shared/support/support.ts
  src/assets/img/homepage/angular-logo.svg
  src/assets/img/homepage/discord-logo.svg
  src/assets/img/homepage/google-groups-logo.png
  src/assets/img/homepage/stackoverflow-logo.svg
  src/assets/img/homepage/twitter-logo.svg
Labels: P3: important, cla: no, pr: lgtm, pr: merge ready

#981 build: updates for v12
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, pr: merge ready

#987 update to 12.0.1
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#991 Setup `@angular/localize` in docs app to enable examples show-casing i18n
  package.json
  src/polyfills.ts
  yarn.lock
Labels: cla: yes, pr: merge ready

#994 feat: expose coercion and collections docs
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes, pr: merge ready

#992 refactor: add modifier badge tag
  src/styles/_api-theme.scss
  src/styles/_api.scss
Labels: cla: yes, pr: merge ready

#995 docs(material/core): Add core API docs
  package.json
  scenes/e2e/src/app.e2e-spec.ts
  scenes/src/app/app-routing.module.ts
  scenes/src/app/scenes/core/core-scene.html
  scenes/src/app/scenes/core/core-scene.scss
  scenes/src/app/scenes/core/core-scene.ts
  src/app/shared/documentation-items/documentation-items.ts
  src/assets/screenshots/autocomplete.scene.png
  src/assets/screenshots/badge.scene.png
  src/assets/screenshots/bottom-sheet.scene.png
  src/assets/screenshots/button-toggle.scene.png
  src/assets/screenshots/button.scene.png
  src/assets/screenshots/card.scene.png
  src/assets/screenshots/checkbox.scene.png
  src/assets/screenshots/chips.scene.png
  src/assets/screenshots/core.scene.png
  src/assets/screenshots/datepicker.scene.png
  src/assets/screenshots/dialog.scene.png
  src/assets/screenshots/divider.scene.png
  src/assets/screenshots/expansion.scene.png
  src/assets/screenshots/form-field.scene.png
  src/assets/screenshots/grid-list.scene.png
  src/assets/screenshots/icon.scene.png
  src/assets/screenshots/input.scene.png
  src/assets/screenshots/list.scene.png
  src/assets/screenshots/menu.scene.png
  src/assets/screenshots/paginator.scene.png
  src/assets/screenshots/progress-bar.scene.png
  src/assets/screenshots/progress-spinner.scene.png
  src/assets/screenshots/radio.scene.png
  src/assets/screenshots/ripple.scene.png
  src/assets/screenshots/select.scene.png
  src/assets/screenshots/sidenav.scene.png
  src/assets/screenshots/slide-toggle.scene.png
  src/assets/screenshots/slider.scene.png
  src/assets/screenshots/snack-bar.scene.png
  src/assets/screenshots/sort.scene.png
  src/assets/screenshots/stepper.scene.png
  src/assets/screenshots/table.scene.png
  src/assets/screenshots/tabs.scene.png
  src/assets/screenshots/toolbar.scene.png
  src/assets/screenshots/tooltip.scene.png
  src/assets/screenshots/tree.scene.png
  yarn.lock
Labels: cla: yes

#990 fix: use theme color for link inside the API reference
  src/styles/_api-theme.scss
Labels: cla: yes

#996 fix: sort links alphabetically
  src/app/shared/documentation-items/documentation-items.ts
Labels: cla: yes

#998 release: bump to 12.0.2
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#988 feat: add cookie popup
  src/_app-theme.scss
  src/app/app-module.ts
  src/app/material-docs-app.html
  src/app/shared/cookie-popup/_cookie-popup-theme.scss
  src/app/shared/cookie-popup/cookie-popup-module.ts
  src/app/shared/cookie-popup/cookie-popup.html
  src/app/shared/cookie-popup/cookie-popup.scss
  src/app/shared/cookie-popup/cookie-popup.ts
Labels: P2: required, cla: yes

#1001 fix: cache fetched docs
  src/app/shared/doc-viewer/doc-viewer.spec.ts
  src/app/shared/doc-viewer/doc-viewer.ts
Labels: cla: yes
