Repository angular/material.angular.io, pull requests merged in 2021-04, with the labels that each got.

#939 build: update to Angular and CLI v12 next.7 and Components v12 next.5
  angular.json
  package.json
  src/app/shared/table-of-contents/table-of-contents.ts
  src/app/shared/theme-picker/theme-picker.spec.ts
  src/app/shared/theme-picker/theme-picker.ts
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  src/assets/versions.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, pr: lgtm

#943 ci: remove PR rebasing from patch branch
  .circleci/config.yml
Labels: P2: required, cla: yes, infrastructure

#941 release: bump to version 11.2.8
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#942 release: update to 12.0.0-next.6
  src/assets/versions.json
Labels: P2: required, cla: yes, dependencies, pr: needs rebase

#944 fix: double scroll bars on guides page
  src/app/pages/guide-list/guide-list.scss
Labels: P3: important, cla: yes

#946 build: update to Angular & CLI v12 next.8, Components v12 next.6
  .circleci/config.yml
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  yarn.lock
Labels: cla: yes

#947 build: update to node 14 and remove dependency
  .circleci/config.yml
  .nvmrc
  package.json
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  yarn.lock
Labels: cla: yes

#951 build: update to Angular and CLI v12 next.9
  package.json
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, pr: lgtm, pr: merge ready

#950 build: give a warning when trying to npm install
  package.json
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
  tools/npm/check-npm.js
  yarn.lock
Labels: P3: important, cla: yes, dependencies, infrastructure, pr: lgtm, pr: merge ready

#952 feat: switch to sass modules
  scenes/src/styles.scss
  src/_app-theme.scss
  src/app/material-docs-app.scss
  src/app/pages/component-category-list/_component-category-list-theme.scss
  src/app/pages/component-category-list/component-category-list.scss
  src/app/pages/component-page-header/component-page-header.scss
  src/app/pages/component-sidenav/_component-sidenav-theme.scss
  src/app/pages/component-sidenav/component-sidenav.scss
  src/app/pages/component-viewer/_component-viewer-theme.scss
  src/app/pages/component-viewer/component-viewer.scss
  src/app/pages/guide-list/_guide-list-theme.scss
  src/app/pages/guide-list/guide-list.scss
  src/app/pages/guide-viewer/guide-viewer.scss
  src/app/pages/homepage/_homepage-theme.scss
  src/app/pages/not-found/_not-found-theme.scss
  src/app/shared/carousel/_carousel-theme.scss
  src/app/shared/example-viewer/_example-viewer-theme.scss
  src/app/shared/footer/_footer-theme.scss
  src/app/shared/navbar/_navbar-theme.scss
  src/app/shared/table-of-contents/_table-of-contents-theme.scss
  src/styles.scss
  src/styles/_api-theme.scss
  src/styles/_constants.scss
  src/styles/_markdown-theme.scss
  src/styles/_svg-theme.scss
  src/styles/_tables-theme.scss
  src/styles/_tables.scss
  src/styles/custom-themes/deeppurple-amber.scss
  src/styles/custom-themes/indigo-pink.scss
  src/styles/custom-themes/pink-bluegrey.scss
  src/styles/custom-themes/purple-green.scss
Labels: P3: important, cla: yes

#954 build: fix compilation errors in scenes
  scenes/src/app/scene-viewer/scene-viewer.ts
  scenes/src/app/scenes/autocomplete/autocomplete-scene.ts
  scenes/src/app/scenes/menu/menu-scene.ts
  scenes/src/app/scenes/ripples/ripples-scene.ts
  scenes/src/app/scenes/select/select-scene.ts
  scenes/src/app/scenes/slider/slider-scene.ts
  scenes/src/app/scenes/tooltip/tooltip-scene.ts
Labels: P2: required, cla: yes, pr: lgtm, pr: merge ready

#953 chore: enable Ivy in StackBlitz examples
  src/assets/stack-blitz-tests/tsconfig.json
  src/assets/stack-blitz/tsconfig.json
Labels: P2: required, cla: yes, infrastructure, pr: lgtm, pr: merge ready

#957 build: switch to eslint
  .eslintrc.json
  angular.json
  package.json
  scenes/.eslintrc.json
  scenes/tslint.json
  src/app/pages/component-sidenav/component-sidenav-can-load-guard.ts
  src/app/pages/component-viewer/component-viewer.ts
  src/app/pages/page-title/page-title.ts
  src/app/routes.ts
  src/app/shared/example-viewer/example-viewer.ts
  src/assets/stack-blitz-tests/src/main.ts
  tslint.json
  yarn.lock
Labels: cla: yes

#956 Update footer copyright from 2020 to 2021
  src/app/shared/footer/footer.html
Labels: P4: nice to have, cla: yes, pr: lgtm

#958 update to 11.2.10
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#959 update to 11.2.10 and reorder versions from newest to oldest
  src/assets/versions.json
Labels: cla: yes

#960 build: update to Angular 12 RC and bump MDC
  package.json
  yarn.lock
Labels: cla: yes

#963 update versions.json for v9.material.angular.io
  src/assets/versions.json
Labels: P3: important, cla: yes, infrastructure

#964 update versions.json for v8.material.angular.io
  src/assets/versions.json
Labels: P3: important, cla: yes, infrastructure

#948 fix(csp): allow img-src of 'self'
  firebase.json
Labels: P2: required, cla: yes, infrastructure, pr: lgtm

#949 fix(csp): allow img-src of 'self' for v11.x
  firebase.json
Labels: P2: required, cla: yes, infrastructure, pr: lgtm

#961 perf: example rendering performance improvements
  src/app/shared/stack-blitz/stack-blitz-button.ts
  src/app/shared/stack-blitz/stack-blitz-writer.spec.ts
  src/app/shared/stack-blitz/stack-blitz-writer.ts
Labels: cla: yes

#965 update 8.x branch to point to latest versions.json file
  firebase.json
  src/app/shared/version-picker/version-picker.ts
  src/assets/versions.json
Labels: P3: important, cla: yes, infrastructure

#969 update to 11.2.11
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#970 update to 12.0.0-rc.1
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#967 chore: update 10.2.x branch to point to latest versions.json file
  firebase.json
  src/app/shared/version-picker/version-picker.ts
  src/assets/versions.json
Labels: cla: yes

#966 chore: update 9.x branch to point to latest versions.json file
  firebase.json
  src/app/shared/version-picker/version-picker.ts
  src/assets/versions.json
Labels: P3: important, cla: yes, infrastructure, pr: lgtm, pr: merge ready

#971 chore: update to Angular and CLI v12 rc.1
  angular.json
  package.json
  yarn.lock
Labels: P2: required, cla: yes, dependencies, infrastructure
