Repository angular/material.angular.io, pull requests merged in 2021-03, with the labels that each got.

#929 release: bump to 11.2.4
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#930 build: update dependencies and add script to optimize scene images
  .gitignore
  firebase.json
  package.json
  scenes/e2e/protractor.conf.js
  src/app/shared/stack-blitz/stack-blitz-writer.ts
  src/assets/screenshots/autocomplete.scene.png
  src/assets/screenshots/badge.scene.png
  src/assets/screenshots/bottom-sheet.scene.png
  src/assets/screenshots/button-toggle.scene.png
  src/assets/screenshots/button.scene.png
  src/assets/screenshots/card.scene.png
  src/assets/screenshots/checkbox.scene.png
  src/assets/screenshots/chips.scene.png
  src/assets/screenshots/datepicker.scene.png
  src/assets/screenshots/dialog.scene.png
  src/assets/screenshots/divider.scene.png
  src/assets/screenshots/expansion.scene.png
  src/assets/screenshots/form-field.scene.png
  src/assets/screenshots/grid-list.scene.png
  src/assets/screenshots/icon.scene.png
  src/assets/screenshots/input.scene.png
  src/assets/screenshots/list.scene.png
  src/assets/screenshots/menu.scene.png
  src/assets/screenshots/paginator.scene.png
  src/assets/screenshots/progress-bar.scene.png
  src/assets/screenshots/progress-spinner.scene.png
  src/assets/screenshots/radio.scene.png
  src/assets/screenshots/ripple.scene.png
  src/assets/screenshots/select.scene.png
  src/assets/screenshots/sidenav.scene.png
  src/assets/screenshots/slide-toggle.scene.png
  src/assets/screenshots/slider.scene.png
  src/assets/screenshots/snack-bar.scene.png
  src/assets/screenshots/sort.scene.png
  src/assets/screenshots/stepper.scene.png
  src/assets/screenshots/table.scene.png
  src/assets/screenshots/tabs.scene.png
  src/assets/screenshots/toolbar.scene.png
  src/assets/screenshots/tooltip.scene.png
  src/assets/screenshots/tree.scene.png
  src/assets/stack-blitz/package.json
  tools/audit-docs.js
  tools/lighthouse-audit.js
  tools/optimize-scene-screenshots.js
  yarn.lock
Labels: P2: required, cla: yes, dependencies, infrastructure, pr: lgtm, pr: merge ready

#931 release: update next.material.angular.io with v12
  package.json
  yarn.lock
Labels: cla: yes

#933 update to angular material 11.2.5
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#934 update angular material to 12.0.0-next.3
  package.json
  yarn.lock
Labels: cla: yes

#689 build: enable strictPropertyInitialization
  src/app/pages/component-category-list/component-category-list.ts
  src/app/pages/component-list/component-list.ts
  src/app/pages/component-sidenav/component-sidenav.ts
  src/app/pages/component-viewer/component-viewer.ts
  src/app/shared/carousel/carousel.spec.ts
  src/app/shared/carousel/carousel.ts
  src/app/shared/doc-viewer/doc-viewer.ts
  src/app/shared/doc-viewer/header-link.ts
  src/app/shared/example-viewer/code-snippet.ts
  src/app/shared/example-viewer/example-viewer.html
  src/app/shared/example-viewer/example-viewer.ts
  src/app/shared/ga/ga.ts
  src/app/shared/navbar/navbar.ts
  src/app/shared/navigation-focus/navigation-focus.service.ts
  src/app/shared/stack-blitz/stack-blitz-button.html
  src/app/shared/stack-blitz/stack-blitz-button.ts
  src/app/shared/svg-viewer/svg-viewer.ts
  src/app/shared/table-of-contents/table-of-contents.ts
  src/app/shared/theme-picker/theme-picker.ts
  tsconfig.json
Labels: P3: important, cla: yes, pr: merge ready

#936 build: update StackBlitz demos to typescript 4.2
  src/assets/stack-blitz-tests/package.json
  src/assets/stack-blitz/package.json
Labels: P2: required, cla: yes, infrastructure, pr: merge ready

#937 update to 11.2.6
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes

#938 update to 12.0.0-next.4
  package.json
  src/assets/versions.json
  yarn.lock
Labels: cla: yes
